# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import email_pb2 as email__pb2


class EmailStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/email.Email/Register',
                request_serializer=email__pb2.Credentials.SerializeToString,
                response_deserializer=email__pb2.Response.FromString,
                )
        self.SendEmail = channel.unary_unary(
                '/email.Email/SendEmail',
                request_serializer=email__pb2.Content.SerializeToString,
                response_deserializer=email__pb2.Response.FromString,
                )
        self.CheckMailbox = channel.unary_stream(
                '/email.Email/CheckMailbox',
                request_serializer=email__pb2.Credentials.SerializeToString,
                response_deserializer=email__pb2.Content.FromString,
                )


class EmailServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckMailbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=email__pb2.Credentials.FromString,
                    response_serializer=email__pb2.Response.SerializeToString,
            ),
            'SendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=email__pb2.Content.FromString,
                    response_serializer=email__pb2.Response.SerializeToString,
            ),
            'CheckMailbox': grpc.unary_stream_rpc_method_handler(
                    servicer.CheckMailbox,
                    request_deserializer=email__pb2.Credentials.FromString,
                    response_serializer=email__pb2.Content.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'email.Email', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Email(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/email.Email/Register',
            email__pb2.Credentials.SerializeToString,
            email__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/email.Email/SendEmail',
            email__pb2.Content.SerializeToString,
            email__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckMailbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/email.Email/CheckMailbox',
            email__pb2.Credentials.SerializeToString,
            email__pb2.Content.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
