# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\x12\x05\x65mail\".\n\x0b\x43redentials\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\">\n\x07\x43ontent\x12\x0f\n\x07to_user\x18\x01 \x01(\t\x12\x11\n\tfrom_user\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\x9c\x01\n\x05\x45mail\x12/\n\x08Register\x12\x12.email.Credentials\x1a\x0f.email.Response\x12,\n\tSendEmail\x12\x0e.email.Content\x1a\x0f.email.Response\x12\x34\n\x0c\x43heckMailbox\x12\x12.email.Credentials\x1a\x0e.email.Content0\x01\x42\x0c\xaa\x02\t_03._gRPCb\x06proto3')



_CREDENTIALS = DESCRIPTOR.message_types_by_name['Credentials']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_CONTENT = DESCRIPTOR.message_types_by_name['Content']
Credentials = _reflection.GeneratedProtocolMessageType('Credentials', (_message.Message,), {
  'DESCRIPTOR' : _CREDENTIALS,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:email.Credentials)
  })
_sym_db.RegisterMessage(Credentials)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:email.Response)
  })
_sym_db.RegisterMessage(Response)

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:email.Content)
  })
_sym_db.RegisterMessage(Content)

_EMAIL = DESCRIPTOR.services_by_name['Email']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\t_03._gRPC'
  _CREDENTIALS._serialized_start=22
  _CREDENTIALS._serialized_end=68
  _RESPONSE._serialized_start=70
  _RESPONSE._serialized_end=111
  _CONTENT._serialized_start=113
  _CONTENT._serialized_end=175
  _EMAIL._serialized_start=178
  _EMAIL._serialized_end=334
# @@protoc_insertion_point(module_scope)
